name: Autism_Helper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk:  '>=2.18.1 <3.0.0'
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.2.1
  audioplayers: ^3.0.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  google_fonts: ^3.0.1
  auto_route: ^5.0.1
  flutter_settings_screens: ^0.3.3-null-safety+2
  confetti: ^0.7.0
  jiffy: ^5.0.0
  image_picker: ^0.8.6
  http: ^0.13.5
  firebase_core: ^2.11.0
  firebase_storage: ^11.1.2
  cloud_firestore: ^4.6.0
  firebase_messaging: ^14.5.0
  firebase_auth: ^4.5.0
  awesome_dialog: ^3.0.2
  dropdown_search: ^5.0.3
  easy_splash_screen: ^1.0.4
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.2.13
  fl_chart: ^0.41.0
  flutter_tflite: ^1.0.1
  camera: ^0.10.3+2
  image: ^3.1.0
  tflite_flutter: ^0.9.0
  camera_android: ^0.10.4+2
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
  image_cropper: ^1.4.1
  flutter_launcher_icons: ^0.9.2
  splashscreen: ^1.3.5-nullsafety.0
  flutter_line_sdk: ^2.3.3

   #tflite_flutter_helper: ^0.3.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  build_runner: ^2.3.0
  auto_route_generator: ^5.0.2
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  #camera: ^0.10.2+1

  #tflite: ^1.1.2
  #tflite_flutter_helper: ^0.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
  assets:
     - assets/sounds/true.wav
     - assets/sounds/false.wav
     - assets/sounds/success.wav
     - assets/sounds/tryAgain.wav
     - assets/images/HomePage/AppIcon.png
     - assets/images/games/animals/lion.png
     - assets/images/games/animals/panda.png
     - assets/images/games/animals/camel.png
     - assets/images/games/animals/dog.png
     - assets/images/games/animals/cat.png
     - assets/images/games/animals/horse.png
     - assets/images/games/animals/sheep.png
     - assets/images/games/animals/fox.png
     - assets/images/games/animals/cow.png
     - assets/images/games/animals/hen.png
     - assets/images/games/faces/cry.png
     - assets/images/games/faces/sad.png
     - assets/images/games/faces/angry.png
     - assets/images/games/faces/happy.png
     - assets/images/games/faces/surprised.png
     - assets/images/games/faces/calm.png
     - assets/images/games/numbers/no0.png
     - assets/images/games/numbers/no1.png
     - assets/images/games/numbers/no2.png
     - assets/images/games/numbers/no3.png
     - assets/images/games/numbers/no4.png
     - assets/images/games/numbers/no5.png
     - assets/images/games/numbers/no6.png
     - assets/images/games/numbers/no7.png
     - assets/images/games/numbers/no8.png
     - assets/images/games/numbers/no9.png
     - assets/images/HomePage/themes1.png
     - assets/images/HomePage/profile.png
     - assets/images/HomePage/requests.jpeg
     - assets/images/HomePage/themes.png
     - assets/images/HomePage/zoo.png
     - assets/images/HomePage/bigFamily.png
     - assets/images/HomePage/games.png
     - assets/images/HomePage/learn.png
     - assets/images/HomePage/AddChild.png
     - assets/images/HomePage/dailySkills.png
     - assets/images/HomePage/registerdChildren.png
     - assets/images/HomePage/family.png
     - assets/images/HomePage/Efaces.png
     - assets/images/HomePage/letters.png
     - assets/images/HomePage/numbers.png
     - assets/images/HomePage/animals.png
     - assets/images/HomePage/defaultPic.png
     - assets/images/games/digits/3ean.png
     - assets/images/games/digits/5a2.png
     - assets/images/games/digits/7a2.png
     - assets/images/games/digits/8ean.png
     - assets/images/games/digits/Alf.png
     - assets/images/games/digits/B.png
     - assets/images/games/digits/daad.png
     - assets/images/games/digits/dal.png
     - assets/images/games/digits/geem.png
     - assets/images/games/digits/heah.png
     - assets/images/games/digits/saad.png
     - assets/images/games/digits/seen.png
     - assets/images/games/digits/sheen.png
     - assets/images/games/digits/T.png
     - assets/images/games/digits/taah.png
     - assets/images/games/digits/tha2.png
     - assets/images/games/digits/waw.png
     - assets/images/games/digits/yeah.png
     - assets/images/games/digits/zaah.png
     - assets/images/games/digits/zal.png
     - assets/images/games/digits/zeen.png
     - assets/images/games/digits/meem.png
     - assets/images/games/digits/noon.png
     - assets/images/games/digits/kaaf.png
     - assets/images/games/digits/laam.png
     - assets/images/games/digits/faa2.png
     - assets/images/games/digits/qaaf.png
     - assets/images/games/digits/raa2.png
     - assets/images/games/family/brothers.png
     - assets/images/games/family/girl.png
     - assets/images/games/family/sister.png
     - assets/images/games/family/father.jpg
     - assets/images/games/family/mother.jpg
     - assets/images/learn/faces/boyHappy.jpg
     - assets/images/learn/faces/boySad.jpg
     - assets/images/learn/faces/girlAngry.jpg
     - assets/images/learn/faces/girlCalm.jpg
     - assets/images/learn/faces/girlHappy.jpg
     - assets/images/learn/faces/girlSad.jpg
     - assets/sounds/learn/faces/girlSad.wav
     - assets/sounds/learn/faces/girlHappy.wav
     - assets/sounds/learn/faces/girlCalm.wav
     - assets/sounds/learn/faces/girlAngry.wav
     - assets/sounds/learn/faces/boySad.wav
     - assets/sounds/learn/faces/boyHappy.wav
     - assets/sounds/learn/numbers/no0.wav
     - assets/sounds/learn/numbers/no1.wav
     - assets/sounds/learn/numbers/no2.wav
     - assets/sounds/learn/numbers/no3.wav
     - assets/sounds/learn/numbers/no4.wav
     - assets/sounds/learn/numbers/no5.wav
     - assets/sounds/learn/numbers/no6.wav
     - assets/sounds/learn/numbers/no7.wav
     - assets/sounds/learn/numbers/no8.wav
     - assets/sounds/learn/numbers/no9.wav
     - assets/images/learn/numbers/no0.jpg
     - assets/images/learn/numbers/no1.jpg
     - assets/images/learn/numbers/no2.jpg
     - assets/images/learn/numbers/no3.jpg
     - assets/images/learn/numbers/no4.jpg
     - assets/images/learn/numbers/no5.jpg
     - assets/images/learn/numbers/no6.jpg
     - assets/images/learn/numbers/no7.jpg
     - assets/images/learn/numbers/no8.jpg
     - assets/images/learn/numbers/no9.jpg
     - assets/sounds/learn/animals/lion.wav
     - assets/sounds/learn/animals/panda.wav
     - assets/sounds/learn/animals/camel.wav
     - assets/sounds/learn/animals/dog.wav
     - assets/sounds/learn/animals/cat.wav
     - assets/sounds/learn/animals/horse.wav
     - assets/sounds/learn/animals/sheep.wav
     - assets/sounds/learn/animals/fox.wav
     - assets/sounds/learn/animals/cow.wav
     - assets/sounds/learn/animals/hen.wav
     - assets/sounds/needs/1.m4a
     - assets/sounds/needs/2.m4a
     - assets/sounds/needs/3.m4a
     - assets/sounds/needs/4.m4a
     - assets/sounds/needs/5.m4a
     - assets/sounds/needs/6.m4a
     - assets/sounds/needs/7.m4a
     - assets/sounds/needs/8.m4a
     - assets/sounds/needs/9.m4a
     - assets/sounds/needs/10.m4a
     - assets/sounds/needs/11.m4a
     - assets/sounds/needs/12.m4a
     - assets/images/needs/1.jpg
     - assets/images/needs/2.jpg
     - assets/images/needs/3.jpg
     - assets/images/needs/4.jpg
     - assets/images/needs/5.jpg
     - assets/images/needs/6.jpg
     - assets/images/needs/7.jpg
     - assets/images/needs/8.jpg
     - assets/images/needs/9.jpg
     - assets/images/needs/10.jpg
     - assets/images/needs/11.jpg
     - assets/images/needs/12.jpg
     - assets/images/learn/digits/3ean.jpg
     - assets/images/learn/digits/5a2.jpg
     - assets/images/learn/digits/7a2.jpg
     - assets/images/learn/digits/8ean.jpg
     - assets/images/learn/digits/Alf.jpg
     - assets/images/learn/digits/B.jpg
     - assets/images/learn/digits/daad.jpg
     - assets/images/learn/digits/dal.jpg
     - assets/images/learn/digits/geem.jpg
     - assets/images/learn/digits/heah.jpg
     - assets/images/learn/digits/saad.jpg
     - assets/images/learn/digits/seen.jpg
     - assets/images/learn/digits/sheen.jpg
     - assets/images/learn/digits/T.jpg
     - assets/images/learn/digits/taah.jpg
     - assets/images/learn/digits/tha2.jpg
     - assets/images/learn/digits/waw.jpg
     - assets/images/learn/digits/yeah.jpg
     - assets/images/learn/digits/zaah.jpg
     - assets/images/learn/digits/zal.jpg
     - assets/images/learn/digits/zeen.jpg
     - assets/images/learn/digits/meem.jpg
     - assets/images/learn/digits/noon.jpg
     - assets/images/learn/digits/kaaf.jpg
     - assets/images/learn/digits/laam.jpg
     - assets/images/learn/digits/faa2.jpg
     - assets/images/learn/digits/qaaf.jpg
     - assets/images/learn/digits/raa2.jpg
     - assets/images/learn/family/father.jpg
     - assets/images/learn/family/mother.jpg
     - assets/images/learn/family/grandFather.jpg
     - assets/images/learn/family/grandMother.jpg
     - assets/images/learn/family/sister.jpg
     - assets/images/learn/family/brother.jpg
     - assets/images/skills/teeth-brushing.png
     - assets/images/skills/door.png
     - assets/images/skills/woman.png
     - assets/images/skills/drink-water.png
     - assets/images/skills/sleep.png
     - assets/images/skills/wash-your-hands.png
     - assets/sounds/learn/family/father.wav
     - assets/sounds/learn/family/mother.wav
     - assets/sounds/learn/family/grandFather.wav
     - assets/sounds/learn/family/grandMother.wav
     - assets/sounds/learn/family/sister.wav
     - assets/sounds/learn/family/brother.wav
     - assets/sounds/learn/digits/3ean.wav
     - assets/sounds/learn/digits/5a2.wav
     - assets/sounds/learn/digits/7a2.wav
     - assets/sounds/learn/digits/8ean.wav
     - assets/sounds/learn/digits/Alf.wav
     - assets/sounds/learn/digits/B.wav
     - assets/sounds/learn/digits/daad.wav
     - assets/sounds/learn/digits/dal.wav
     - assets/sounds/learn/digits/geem.wav
     - assets/sounds/learn/digits/heah.wav
     - assets/sounds/learn/digits/saad.wav
     - assets/sounds/learn/digits/seen.wav
     - assets/sounds/learn/digits/sheen.wav
     - assets/sounds/learn/digits/T.wav
     - assets/sounds/learn/digits/taah.wav
     - assets/sounds/learn/digits/tha2.wav
     - assets/sounds/learn/digits/waw.wav
     - assets/sounds/learn/digits/yeah.wav
     - assets/sounds/learn/digits/zaah.wav
     - assets/sounds/learn/digits/zal.wav
     - assets/sounds/learn/digits/zeen.wav
     - assets/sounds/learn/digits/meem.wav
     - assets/sounds/learn/digits/noon.wav
     - assets/sounds/learn/digits/kaaf.wav
     - assets/sounds/learn/digits/laam.wav
     - assets/sounds/learn/digits/faa2.wav
     - assets/sounds/learn/digits/qaaf.wav
     - assets/sounds/learn/digits/raa2.wav
     - assets/sounds/learn/digits/raa2.wav
     - assets/images/learn/themes/playing.jpg
     - assets/images/learn/themes/reading.jpg
     - assets/images/learn/themes/eating.jpg
     - assets/images/learn/themes/party.jpg
     - assets/sounds/learn/themes/party.wav
     - assets/sounds/learn/themes/reading.wav
     - assets/sounds/learn/themes/eating.wav
     - assets/sounds/learn/themes/playing.wav
     - assets/sounds/learn/faces/angry.wav
     - assets/sounds/learn/faces/happy.wav
     - assets/sounds/learn/faces/sad.wav
     - assets/sounds/learn/faces/calm.wav
     - assets/sounds/learn/faces/surprise.wav
     - assets/sounds/learn/faces/cry.wav
     - assets/images/HomePage/signInLogo.png
     - assets/images/HomePage/startPage.jpg
     - assets/images/HomePage/trainer.png
     - assets/images/HomePage/discover1.jpg
     - assets/images/HomePage/sideBarBackground.jpg
     - assets/images/HomePage/parent.png
     - assets/images/HomePage/WhatsAppImage.jpeg
     - assets/images/HomePage/discover.png
     - assets/images/skills/shoes.png
     - assets/videos/wear_shoes.mp4
     - assets/videos/wash_hand.mp4
     - assets/videos/eat_food.mp4
     - assets/videos/make_bed.mp4
     - assets/videos/brush_teeth.mp4
     - assets/objecDetec/detect.tflite
     - assets/objecDetec/labelmap.txt
     - assets/objecDetec/yolov7labels1.txt
     - assets/objecDetec/yolov2_tiny.txt
     - assets/objecDetec/yolov2_tiny.tflite
     - assets/objecDetec/SSDlabels.txt
     - assets/objecDetec/SSDlabelsArabic.txt
     - assets/objecDetec/ssd_mobilenet.tflite
     - assets/objecDetec/yolov7-tiny.tflite
     - assets/objecDetec/mobilenet_v1_1.0_224.tflite
     - assets/objecDetec/mobilenet_v1_1.0_224.txt
     - assets/sounds/objectDetec/اتوبيس.wav
     - assets/sounds/objectDetec/اشارة مرور.wav
     - assets/sounds/objectDetec/بقرة.wav
     - assets/sounds/objectDetec/حصان.wav
     - assets/sounds/objectDetec/خاروف.wav
     - assets/sounds/objectDetec/دراجة نارية.wav
     - assets/sounds/objectDetec/سيارة.wav
     - assets/sounds/objectDetec/شاحنة نقل.wav
     - assets/sounds/objectDetec/person.wav
     - assets/sounds/objectDetec/صنبور الاطفاء.wav
     - assets/sounds/objectDetec/طائر.wav
     - assets/sounds/objectDetec/طائرة.wav
     - assets/sounds/objectDetec/عجلة.wav
     - assets/sounds/objectDetec/عداد موقف السيارات.wav
     - assets/sounds/objectDetec/علامة وقوف.wav
     - assets/sounds/objectDetec/قطار.wav
     - assets/sounds/objectDetec/قطة.wav
     - assets/sounds/objectDetec/كلب.wav
     - assets/sounds/objectDetec/مركب.wav
     - assets/sounds/objectDetec/مقعد.wav
     #- assets/objecDetec/yolov7_model.tflite
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
